"""token de whatsapp por cliente, cifrado

Revision ID: c2533a810321
Revises: fd9e6df17d1c
Create Date: 2026-08-05 13:20:45.968888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2533a810321'
down_revision: Union[str, Sequence[str], None] = 'fd9e6df17d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('whatsapp_access_token_cifrado', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'whatsapp_access_token_cifrado')
    # ### end Alembic commands ###
