"""cuotas: tenant_usage y limite mensual por cliente

Revision ID: c72a8511a449
Revises: bfd8221dcf7c
Create Date: 2026-07-29 15:33:19.838964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72a8511a449'
down_revision: Union[str, Sequence[str], None] = 'bfd8221dcf7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('messages', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_usage_tenant_id'), 'tenant_usage', ['tenant_id'], unique=False)
    op.create_index('uq_tenant_usage_tenant_period', 'tenant_usage', ['tenant_id', 'period'], unique=True)
    op.add_column('tenants', sa.Column('monthly_message_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # AGREGADO A MANO. La columna es nullable y NULL significa "sin limite", asi
    # que sin este backfill todos los clientes que ya existen quedarian sin tope
    # justo en la migracion que introduce las cuotas.
    #
    # El valor esta escrito literal y no leido de settings a proposito: una
    # migracion tiene que producir el mismo resultado siempre, sin importar la
    # configuracion del entorno donde se corra ni cuando se corra.
    op.execute("UPDATE tenants SET monthly_message_limit = 2000 WHERE monthly_message_limit IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'monthly_message_limit')
    op.drop_index('uq_tenant_usage_tenant_period', table_name='tenant_usage')
    op.drop_index(op.f('ix_tenant_usage_tenant_id'), table_name='tenant_usage')
    op.drop_table('tenant_usage')
    # ### end Alembic commands ###
