"""agregar processed_events para idempotencia de webhooks

Revision ID: e3d3ae7e677b
Revises: d266ff30bfe9
Create Date: 2026-07-29 15:00:58.380807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d3ae7e677b'
down_revision: Union[str, Sequence[str], None] = 'd266ff30bfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processed_events_status', 'processed_events', ['status'], unique=False)
    op.create_index(op.f('ix_processed_events_tenant_id'), 'processed_events', ['tenant_id'], unique=False)
    op.create_index('uq_processed_events_channel_external_id', 'processed_events', ['channel', 'external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_processed_events_channel_external_id', table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_tenant_id'), table_name='processed_events')
    op.drop_index('ix_processed_events_status', table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
