"""memoria conversacional: orden de mensajes y ventana de inactividad

Revision ID: fd9e6df17d1c
Revises: c72a8511a449
Create Date: 2026-07-29 19:09:35.345844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9e6df17d1c'
down_revision: Union[str, Sequence[str], None] = 'c72a8511a449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_conversations_last_activity_at'), 'conversations', ['last_activity_at'], unique=False)
    op.create_index('ix_conversations_lookup', 'conversations', ['tenant_id', 'channel', 'external_id'], unique=False)
    # CORREGIDO A MANO. --autogenerate emitia:
    #     op.add_column('messages', sa.Column('position', sa.Integer(), nullable=False))
    # Eso funciona solo si la tabla esta vacia. Con filas existentes, Postgres
    # rechaza agregar una columna NOT NULL sin default:
    #     column "position" of relation "messages" contains null values
    # Hoy `messages` esta vacia, asi que el error habria aparecido recien en
    # staging o produccion. El patron correcto son tres pasos:
    op.add_column('messages', sa.Column('position', sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE messages m
        SET position = orden.rn
        FROM (
            SELECT id,
                   ROW_NUMBER() OVER (
                       PARTITION BY conversation_id ORDER BY created_at, id
                   ) AS rn
            FROM messages
        ) AS orden
        WHERE m.id = orden.id
        """
    )
    op.alter_column('messages', 'position', nullable=False)
    op.create_index('ix_messages_orden', 'messages', ['conversation_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_orden', table_name='messages')
    op.drop_column('messages', 'position')
    op.drop_index('ix_conversations_lookup', table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_activity_at'), table_name='conversations')
    op.drop_column('conversations', 'last_activity_at')
    # ### end Alembic commands ###
